---
- name: Filter templates for this node
  ansible.builtin.set_fact:
    host_templates: "{{ vms | selectattr('node','equalto', inventory_hostname) | list }}"

- name: Nothing to do on this node
  ansible.builtin.debug:
    msg: "No templates targeted for {{ inventory_hostname }}."
  when: host_templates | length == 0
  changed_when: false

- name: Build each template on this node
  ansible.builtin.include_tasks: create_template.yml
  loop: "{{ host_templates }}"
  loop_control:
    loop_var: tmpl
    label: "{{ tmpl.name }} (vmid={{ tmpl.vmid }})"