---
- name: Allocate a cluster-unique VMID for the template
  ansible.builtin.command: pvesh get /cluster/nextid
  register: nextid
  changed_when: false

- name: Set fact for template_vmid
  ansible.builtin.set_fact:
    template_vmid: "{{ nextid.stdout | int }}"

- name: Create empty VM (template shell)
  ansible.builtin.command: >
    qm create {{ template_vmid }}
    --name {{ cloudinit.template_name }}
    --memory 2048
    --cores 1
    --net0 virtio,bridge=vmbr0
    --scsihw virtio-scsi-pci
    --ostype l26
  args:
    creates: "/etc/pve/qemu-server/{{ template_vmid }}.conf"

- name: Import downloaded disk into storage
  ansible.builtin.command: >
    qm importdisk {{ template_vmid }}
    "/var/lib/vz/template/images/{{ cloudinit.img_name }}"
    local-lvm
  register: import_out
  changed_when: "'Successfully imported' in import_out.stdout or import_out.stderr"

- name: Attach imported disk as scsi0
  ansible.builtin.command: >
    qm set {{ template_vmid }}
    --scsi0 local-lvm:vm-{{ template_vmid }}-disk-0
    --boot order=scsi0
  changed_when: true

- name: Add cloud-init drive
  ansible.builtin.command: >
    qm set {{ template_vmid }} --ide2 local-lvm:cloudinit
  changed_when: true

- name: Enable QEMU guest agent
  ansible.builtin.command: >
    qm set {{ template_vmid }} --agent enabled=1
  changed_when: true

- name: Resize root disk
  ansible.builtin.command: >
    qm resize {{ template_vmid }} scsi0 +20G
  changed_when: true

- name: Convert to template
  ansible.builtin.command: qm template {{ template_vmid }}
  changed_when: true

- name: Debug template created
  ansible.builtin.debug:
    msg: "Template {{ cloudinit.template_name }} (vmid={{ template_vmid }}) created on {{ inventory_hostname }}"
