---
- name: Ensure namespace exists
  ansible.builtin.shell: |
    kubectl {{ kubectl_args }} get ns {{ metallb_namespace }} >/dev/null 2>&1 \
    || kubectl {{ kubectl_args }} create ns {{ metallb_namespace }}
  changed_when: false

- name: Add/update MetalLB helm repo
  ansible.builtin.shell: |
    helm repo add {{ metallb_repo_name }} {{ metallb_repo_url }} >/dev/null 2>&1 || true
    helm repo update {{ helm_args }}
  changed_when: false

- name: Install/upgrade MetalLB
  ansible.builtin.shell: |
    helm upgrade --install {{ metallb_release }} {{ metallb_chart }} \
      --namespace {{ metallb_namespace }} \
      {{ ('--version ' ~ metallb_version) if metallb_version else '' }} \
      {{ helm_args }}
  changed_when: "'Release ' in (stdout | default('')) or 'deployed' in (stdout | default(''))"

# Create the pool + L2Advertisement
- name: Build MetalLB pool + L2Advertisement
  ansible.builtin.set_fact:
    metallb_pool_doc:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: "{{ metallb_pool_name }}"
        namespace: "{{ metallb_namespace }}"
      spec:
        addresses: "{{ metallb_addresses }}"
    metallb_l2_doc:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: l2
        namespace: "{{ metallb_namespace }}"
      spec:
        ipAddressPools:
          - "{{ metallb_pool_name }}"

- name: Write MetalLB manifest (YAML-safe)
  ansible.builtin.copy:
    dest: /tmp/metallb-pool.yml
    mode: "0644"
    content: |
      {{ metallb_pool_doc | to_nice_yaml(indent=2) }}---
      {{ metallb_l2_doc | to_nice_yaml(indent=2) }}

- name: Read rendered manifest
  ansible.builtin.slurp:
    src: /tmp/metallb-pool.yml
  register: poolfile

- name: Show rendered manifest (debug)
  ansible.builtin.debug:
    msg: "{{ poolfile.content | b64decode }}"

- name: Apply MetalLB pool manifest
  ansible.builtin.shell: kubectl {{ kubectl_args }} apply -f /tmp/metallb-pool.yml
  register: metallb_apply
  changed_when: "'created' in (metallb_apply.stdout | default('')) or 'configured' in (metallb_apply.stdout | default(''))"

- name: Wait for MetalLB controller/speaker to be ready
  ansible.builtin.shell: kubectl {{ kubectl_args }} -n {{ metallb_namespace }} rollout status deploy/{{ metallb_release }}-controller --timeout=120s
  register: metallb_rollout
  changed_when: false
