---
- name: Build Ubuntu cloud-init template on Proxmox
  hosts: proxmox_hosts
  gather_facts: false
  become: true
  vars:
    primary_host: "{{ groups['proxmox_hosts'][0] }}"
  tasks:
    - name: Only run roles on the first Proxmox host
      delegate_to: "{{ primary_host }}"
      block:
        - import_role:
            name: cloudinit-download_cloud_image
        - import_role:
            name: cloudinit-create_template
