---
- name: Build Ubuntu cloud-init template on Proxmox
  hosts: proxmox_template_host
  gather_facts: false
  become: true

  roles:
    - role: cloudinit-get_cloud_image     # downloads/ensures the cloud image
    - role: cloudinit-create_template     # builds/updates the cloud-init template