---
- name: Build Ubuntu cloud-init template on Proxmox
  hosts: proxmox_hosts
  gather_facts: false
  become: true
  tasks:
    - name: Only run roles on the first Proxmox host
      run_once: true
      delegate_to: "{{ groups['proxmox_hosts'][0] }}"
      block:
        - import_role:
            - name: cloudinit-download_cloud_image
        - import_role:
            - name: cloudinit-create_template
