---
- name: Check sshpass
  hosts: local
  gather_facts: true
  become: true
  roles:
    - base-check-sshpass

- name: Build Ubuntu cloud-init template on Proxmox
  hosts: primary_host
  gather_facts: false
  become: true
  roles:
    - cloudinit-get_cloud_image
    - cloudinit-create_template