---
- name: Generate inventory
  import_playbook: 0100-generate_inventory.yml

- name: Preconfigure VMs
  import_playbook: 0200-preconfigure_vms.yml

- name: Install k3s on all nodes
  import_playbook: 0300-install_k3.yml

- name: Setup local env
  import_playbook: 0310-setup_local_env.yml
