# Disable swap: sudo sed -i '/ swap / s/^/#/' /etc/fstab

- name: Check if any swap is active
  ansible.builtin.command: swapon --noheadings
  register: swapon_out
  changed_when: false
  failed_when: false

- name: Disable swap immediately
  ansible.builtin.command: swapoff -a
  when: swapon_out.stdout != ""
  become: true

- name: Disable swap persistently in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^\s*([^#].*\s+swap\s+.*)$'
    replace: '# \1'
    backup: true
  become: true

- name: Verify swap is disabled
  ansible.builtin.command: swapon --show
  register: verify_swap
  changed_when: false

- name: Print verification
  ansible.builtin.debug:
    msg: >-
      Swap devices listed: '{{ verify_swap.stdout_lines | default([]) }}'
      (empty means swap is disabled)