# == Current specifications == 
  # current image: ubuntu-24.04.2-live-server-amd64.iso

  # proxmox1.storage: 200G (SSD)
  # proxmox1.sockets: 1
  # proxmox1.cores: 8
  # proxmox1.mem: 15 GiB

  # proxmox2.storage: 725G (SSD)
  # proxmox2.sockets: 1
  # proxmox2.cores: 8
  # proxmox2.mem: 15 GiB

  # proxmox3.storage: 8980G (HDD)
  # proxmox3.sockets: 1
  # proxmox3.cores: 8
  # proxmox3.mem: 15 GiB

# ==== Cloudinit ====
cloudinit_template:
  # Cloud image (Ubuntu 24.04 LTS)
  img_url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
  img_dir: "/var/lib/vz/template/iso"
  # Optional: override. If omitted, derived from img_url basename under img_dir
  img_file: ""


# ==== Proxmox API ====
# Use the proxmox_create_token.sh script to generate the api_token_id and api_token_secret
proxmox:
  api_host: "192.168.1.30"
  api_user: "ansible@pve"
  api_token_id: "ansible@pve!ansible"
  api_token_secret: "59ede7aa-3fff-45cb-9c6c-2f86471e9d93"
  validate_certs: false
  ssh_user: root
  nodes:
    - { name: "proxmox1" }
    - { name: "proxmox2" }
    - { name: "proxmox3" }
  placement:
    strategy: round_robin


# ==== Network defaults for cloud-init ====
network:
  cidr: 24
  gateway_ip: 192.168.1.1
  nameservers: [192.168.1.1, 1.1.1.1]
  ntp_ip: 192.168.1.1
  domain: lab


# ===== VM Defaults (inherited by groups/overrides) =====
# If source_template is specified it will use that, if not it will use iso_image
vm_defaults:
  storage: "local-lvm"
  bridge: "vmbr0"
  sockets: 1
  cores: 5
  memory_gib: 8
  disk_gb: 100
  template_name: "ubuntu-24.04-noble-ci-template"
  ciuser: "psubedi"
  ssh_authorized_keys: []
  vmid_autogenerate: true
  cpu_type: "host"
  ballon: 0
  hotplug: "disk,network,usb,memory,cpu"
  multiqueue: 4
  scsihw: "virtio-scsi-single"
  onboot: true


# ===== VM groups -> produces k3-node-1...3 across nodes =====
vm_groups:
  - name_prefix: "k3-node"
    count: 3
    start_index: 1
    name_pad: 2
    node_strategy: round_robin
    base:
      sockets: 1
      cores: 5
      memory_gib: 8
      disk_gb: 100
    overrides:
      - index: 1
        hostname: "k3-node-1"
        ip: 192.168.1.40
        node: "proxmox1"
      - index: 2
        hostname: "k3-node-2"
        ip: 192.168.1.41
        node: "proxmox2"
      - index: 3
        hostname: "k3-node-3"
        ip: 192.168.1.42
        node: "proxmox3"
