# ==== Proxmox API ====
# Use the proxmox_create_token.sh script to generate the api_token_id and api_token_secret
proxmox:
  api_host: "192.168.1.30"
  api_user: "ansible@pve"
  api_user_password: "Subedi10!"
  api_token_id: "ansible@pve!ansible"
  api_token_secret: "59ede7aa-3fff-45cb-9c6c-2f86471e9d93"
  validate_certs: false
  ssh_user: root


# ==== Cloudinit ====
# Cloud image: Ubuntu 24.04 LTS
# if img_file blank, derive from img_url basename under img_dir
cloudinit:
  img_url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
  img_dir: "/var/lib/vz/template/iso"
  img_file: ""
  template_name: "ubuntu-2404-cloudinit"
  template_id: 9000
  node: "proxmox1"
  storage: "local-lvm"
  ciuser: psubedi
  inject_ssh_key: true


# ==== Network ====
network:
  cidr: 24
  gateway_ip: 192.168.1.1
  nameservers: [192.168.1.1, 1.1.1.1]
  ntp_ip: 192.168.1.1
  domain: lab


# == Current specifications == 
  # current image: ubuntu-24.04.2-live-server-amd64.iso

  # proxmox1.storage: 200G (SSD)
  # proxmox1.sockets: 1
  # proxmox1.cores: 8
  # proxmox1.mem: 15 GiB

  # proxmox2.storage: 725G (SSD)
  # proxmox2.sockets: 1
  # proxmox2.cores: 8
  # proxmox2.mem: 15 GiB

  # proxmox3.storage: 8980G (HDD)
  # proxmox3.sockets: 1
  # proxmox3.cores: 8
  # proxmox3.mem: 15 GiB

# ===== VMs =====
vms:
  - hostname: "k3-node-1"
    ip: 192.168.1.40
    node: "proxmox1"
    mem_mb: 8192
    cores: 5
    sockets: 1
    disk_gb: 50
    ssd: true
  - hostname: "k3-node-2"
    ip: 192.168.1.41
    node: "proxmox2"
    mem_mb: 8192
    cores: 5
    sockets: 1
    disk_gb: 100
    ssd: true
  - hostname: "k3-node-3"
    ip: 192.168.1.42
    node: "proxmox3"
    mem_mb: 8192
    cores: 5
    sockets: 1
    disk_gb: 300
    ssd: false

