# Install chrony and verify on each VM
#sudo apt update
#sudo systemctl stop systemd-timesyncd.service
#sudo systemctl disable systemd-timesyncd.service
#sudo apt -y purge systemd-timesyncd
#sudo apt install -y chrony
#sudo systemctl enable --now chrony
#copy /etc/chrony/chrony.conf 
#sudo systemctl restart chrony
#sudo systemctl status chrony
