---
- name: Check if sshpass is already installed
  command: which sshpass
  register: sshpass_check
  changed_when: false
  failed_when: false

- name: Show sshpass path if already installed
  debug:
    msg: "✅ sshpass installed at {{ sshpass_check.stdout }}"
  when: sshpass_check.rc == 0

- name: Install sshpass (Debian or RedHat family)
  package:
    name: "sshpass"
    state: present
  when:
    - sshpass_check.rc != 0
    - ansible_facts['os_family'] in ['Debian', 'RedHat']

- name: Inform user if sshpass was installed just now
  debug:
    msg: "✅ sshpass has been successfully installed."
  when: sshpass_check.rc != 0