---
- name: Derive image file path when not provided
  ansible.builtin.set_fact:
    _ci_img_file: >-
      {{ (cloudinit_template.img_file | length > 0)
         | ternary(cloudinit_template.img_file,
                   cloudinit_template.img_dir ~ '/' ~ (cloudinit_template.img_url | basename)) }}

- name: Ensure image directory exists
  ansible.builtin.file:
    path: "{{ cloudinit_template.img_dir }}"
    state: directory
    mode: "0755"
  tags: [download]

- name: Download Ubuntu cloud image if missing
  ansible.builtin.get_url:
    url: "{{ cloudinit_template.img_url }}"
    dest: "{{ _ci_img_file }}"
    mode: "0644"
  args:
    creates: "{{ _ci_img_file }}"
  tags: [download]

- name: Show image path
  ansible.builtin.debug:
    msg: "Cloud image ready at {{ _ci_img_file }}"
  tags: [download]
