# Downloads image to /var/lib/vz/template/iso/noble-server-cloudimg-amd64.img
---
- name: Derive image file path when not provided
  ansible.builtin.set_fact:
    _ci_img_file: >-
      {{ (cloudinit.img_file | length > 0)
         | ternary(cloudinit.img_file,
                   cloudinit.img_dir ~ '/' ~ (cloudinit.img_url | basename)) }}

- name: Ensure image directory exists
  ansible.builtin.file:
    path: "{{ cloudinit.img_dir }}"
    state: directory
    mode: "0755"
  tags: [download]

- name: Check if cloud image already exists (remote)
  ansible.builtin.stat:
    path: "{{ _ci_img_file }}"
  register: img_stat

- name: Download Ubuntu cloud image if missing
  ansible.builtin.get_url:
    url: "{{ cloudinit.img_url }}"
    dest: "{{ _ci_img_file }}"
    mode: "0644"
  when: not img_stat.stat.exists
  tags: [download]

- name: Show image path
  ansible.builtin.debug:
    msg: "Cloud image ready at {{ _ci_img_file }}"
  tags: [download]
