---
- name: Ensure image directory exists
  ansible.builtin.file:
    path: "/var/lib/vz/template/images"
    state: directory
    mode: "0755"

- name: Download Ubuntu Minimal cloud image
  ansible.builtin.get_url:
    url: "{{ cloudinit.img_url }}"
    dest: "/var/lib/vz/template/images/{{ cloudinit.img_name }}"
    mode: "0644"
    force: false

- name: Show downloaded image path
  ansible.builtin.debug:
    msg: "Image downloaded to /var/lib/vz/template/images/{{ cloudinit.img_name }}"
