---
- name: Start Proxmox VM using API token
  ansible.builtin.uri:
    url: "https://{{ proxmox.api_host }}/api2/json/nodes/{{ vm.node }}/qemu/{{ chosen_vmid }}/status/start"
    method: POST
    headers:
      Authorization: "PVEAPIToken={{ proxmox.api_token_id }}={{ proxmox.api_token_secret }}"
    validate_certs: false
    status_code: 200
  loop: "{{ vms }}"
  loop_control:
    loop_var: vm
    label: "{{ vm.hostname }}"

- name: Wait for SSH (port 22) on each VM
  ansible.builtin.wait_for:
    host: "{{ vm.ip }}"
    port: 22
    timeout: 600
    sleep: 5
  loop: "{{ vms }}"
  loop_control:
    loop_var: vm
    label: "{{ vm.hostname }}"
